package com.miaoshaproject.dao;

import com.miaoshaproject.dataObjec.ItemDo;
import com.miaoshaproject.dataObjec.ItemStockDo;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ItemDoMapper {

    // 商品列表浏览
    List<ItemDo> listItem();

    ItemStockDo selectByItemId(String itemId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jul 16 11:44:49 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jul 16 11:44:49 CST 2019
     */
    int insert(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jul 16 11:44:49 CST 2019
     */
    int insertSelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jul 16 11:44:49 CST 2019
     */
    ItemDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jul 16 11:44:49 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Tue Jul 16 11:44:49 CST 2019
     */
    int updateByPrimaryKey(ItemDo record);

    /**
     * 增加销量
     * @param id
     * @param amount
     * @return
     */
    int increaseSales(@Param("id") String id, @Param("amount")Integer amount);
}